name: Release iHome main application

on:
  workflow_dispatch:

env:
  REGISTRY: 172.30.0.1:5000
  IMAGE_NAME: ihome-front:latest
  MKS_DEPLOY_NAME: ihome-front-deploy


jobs:
    dev:
      runs-on: ubuntu-latest
      environment: 'dev'
      defaults:
        run:
          working-directory: ./src
  
      steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
      - name: Add insecure registry
        run: dockerd --insecure-registry http://${{ env.REGISTRY }}
      - name: Docker push
        run: docker push --disable-content-trust=true http://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # - name: Kubernetes context
      #   uses: Azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
      # - name: Kubernetes restart
      #   run: kubectl rollout restart deploy ${{ MKS_DEPLOY_NAME }}
