name: Release iHome main application

on:
  workflow_dispatch:

env:
  REGISTRY: 172.30.0.1:5000
  IMAGE_NAME: ihome-front


jobs:
    release-dev:
      runs-on: ubuntu-latest
      environment: 'dev'
      defaults:
        run:
          working-directory: ./src
  
      steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
      - uses: actions/checkout@v3
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $REGISTRY/$IMAGE_NAME:latest
