name: Release iHome main application

on:
  workflow_dispatch:

env:
  REGISTRY: 172.30.0.1:5000
  IMAGE_NAME: ihome-front:latest
  MKS_DEPLOY_NAME: ihome-front-deploy


jobs:
    dev:
      runs-on: ubuntu-latest
      environment: 'dev'
      defaults:
        run:
          working-directory: ./src
  
      steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
      - name: Docker push
        run: docker push ${{ env.IMAGE_FULL_NAME }} --insecure-registry=${{ env.REGISTRY }}
      # - name: Kubernetes restart
      #   run: kubectl rollout restart deploy ${{ MKS_DEPLOY_NAME }}
