# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build iHome main application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: ZeroTier
      uses: zerotier/github-action@v1
      with:
        network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Add Internal Source
      run: dotnet nuget add source ${{ secrets.INTERNAL_PACKAGES_SOURCE }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Use Node.js 18.17.0
      uses: actions/setup-node@v1
      with:
        node-version: 18.17.0
    - name: Install angular dependencies
      run: yarn install
      working-directory: ./src/iHome/ClientApp
    - name: Angular Lint
      run: ng lint
      working-directory: ./src/iHome/ClientApp
    - name: Angular Test
      run: ng test --browsers ChromeHeadless
      working-directory: ./src/iHome/ClientApp
